[package]
name = "goosling"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.1.8"
rand = {version = "0.8.5", default-features = false, features = ["small_rng"]}
x86_64 = "0.14.10"
static_assertions = "1.1.0"