name: Build
on: push
jobs:
  build:
    env:
      working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: "Test"
        run: cat makefile | xargs echo
      - name: "Make debug"
        run: make iso
      - name: "Make release"
        run: env RELEASE=1 make iso