name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: "x86_64-unknown-none"
      - name: "Make debug"
        run: make iso
      - name: "Make release"
        run: env RELEASE=1 make iso